spring.application.name=demo

spring.datasource.url=jdbc:postgresql://localhost:5433/bookingdb
spring.datasource.username=booking
spring.datasource.password=booking

spring.flyway.enabled=true

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
